openapi: 3.0.1
info:
  title: '@jupiterone/graph-hubspot'
  description: A JupiterOne Integration
  x-cortex-git:
    github:
      repository: JupiterOne/graph-hubspot
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-hubspot'
  x-cortex-service-groups:
    - tier-4
